### ISSUE TITLE
Datepicker not working in a nested container

### ISSUE THREAD

**Issue by arunspawoz** [tritum/repeatable_form_elements#1]
Hi,

I've included a datepicker field in my form and it is working fine in the first section. When I click on the "copy" button, the form fields are repeating, but the datepicker field is not working.

Any solution?

Thank you.

**Comment by arunspawoz** [comment]
Thanks for the quick feedback. Unfortunately, I don't have enough time to look at this issue now. Is it possible for you to provide a fix for this?
Thank you.

**Comment by tritumRz** [comment]
Feel free to test the current master version.

**Comment by arunspawoz** [comment]
Hi,

Thank for the quick fix. Seems to be it is working well.

**Comment by tritumBj** [comment]
Awesome dude! Thanks for testing.
