### ISSUE TITLE
repeatable_form_elements broken in 9.5.25 

### ISSUE THREAD

**Issue by magicHatOfTYPO3** [tritum/repeatable_form_elements#13]
we use this extension in a 9.5 environment using FileUpload-Fields. Until 9.5.24 this is working fine, but as of 9.5.25 we get error messages like

`Failed to process FormValue at "repeatablecontainer-1.1.imageupload-1" from "array" to "TYPO3\CMS\Extbase\Domain\Model\FileReference"`

This problem happens still early in the process in the Middleware-Stack processing this line (which is fairly standard in TYPO3 middleware) `return $handler->handle($request);`

The problem still happens in 9.5.26 and disappears when downgrading to 9.5.24, so it seems related to https://github.com/TYPO3/TYPO3.CMS/commit/66b75cecab 

Do you have any idea how to fix this (in repeatable_form_elements or core or own extension)?

**Comment by pnoreck** [comment]
We have the same issue.

**Comment by pnoreck** [comment]
TYPO3\\CMS\\Extbase\\Property\\Exception\\InvalidPropertyMappingConfigurationException: It is not allowed to map property \"name\". 
You need to use $propertyMappingConfiguration->allowProperties('name') to enable mapping of this property. 
in ~/typo3/sysext/extbase/Classes/Property/PropertyMapper.php:179

**Comment by tritum** [comment]
PR has been merged to master. Will push a new version soon.
