### ISSUE TITLE
Duplicate random clone IDs can be created in RepeatableContainer.js

### ISSUE THREAD

**Issue by localhorst** [tritum/repeatable_form_elements#15]
We have this code in Resources/Public/JavaScript/Form/Frontend/RepeatableContainer.js:56:

`newId = Math.floor(Math.random() * 42) + Date.now();`

It creates a random id for a repetable container clone, but the multiplier 43 is not large enough to avoid duplicates. 

Cheap solution: 
`newId = Math.floor(Math.random() * 99999999) + Date.now();`

Advanced solution: 
Create a globally unique random uid in JavaScript.

**Comment by tritum** [comment]
Thank you for your contribution. I have merged your PR. Thanks!
