### ISSUE TITLE
Composer version constraint

### ISSUE THREAD

**Issue by dr2okevin** [tritum/repeatable_form_elements#27]
Currently the version constraint is fixed to TYPO3 11.5.13. that means that I can't install the Extension in version 11.5.14 or 11.5.12.
Why not 11.5.* ?

**Comment by tritum** [comment]
Thank you for your report. @eliashaeussler has taken care of some cleanup and I did some streamlining as well. I have just tagged version 3.1.0. I will push a new release to TER in a sec. Closing this issue, friends.
