### ISSUE TITLE
Undefined array key "_originalIdentifier" in CopyService.php line 299

### ISSUE THREAD

**Issue by imminger** [tritum/repeatable_form_elements#28]
With TYPO3 11.5.16, EXT:form 11.5.16 and PHP 8.0.18 an error occurs when a form with repeatable form elements is submitted. Issue might be caused by PHP 8.0.

Steps to reproduce issue:
1. Insert attached sample form.yaml on page ([Test Form.zip])(https://github.com/tritum/repeatable_form_elements/files/9734280/Test.Form.zip)
2. Go to frontend, fill out form and put at least 2 values in repeatable container
3. Submit form

Result: PHP Warning: Undefined array key "_originalIdentifier" in /var/www/html/packages/repeatable_form_elements/Classes/Service/CopyService.php line 299

![Bildschirmfoto 2022-10-07 um 15 26 40](https://user-images.githubusercontent.com/15834641/194564652-752c9fc0-0bd7-4c09-ab4b-872479371704.png)

**Comment by ma-gu-16** [comment]
same error here.

**Comment by tritum** [comment]
I've just merged the patch. Thank you guys for bringing this up to our attention.
