### ISSUE TITLE
Error in TYPO3 9.5.4

### ISSUE THREAD

**Issue by julescakecrumb** [tritum/repeatable_form_elements#3]
I integrated repeatable_form_elements to my TYPO3 9.5.4 installation.
The backend works great, but i get an error message (frontend) "TYPO3\CMS\Extbase\Reflection\Exception\UnknownClassException".

Thankful for any advice.

**Comment by kaystrobach** [comment]
Composer installation or via extensionmanager?

**Comment by julescakecrumb** [comment]
@kaystrobach We have a composer installation (already updated to 9.5.5)

**Comment by kaystrobach** [comment]
which version have you installed? a tagged one or master?

**Comment by julescakecrumb** [comment]
@kaystrobach we just found the problem - the symlink in our typo3conf/ext folder was faulty. Everything works fine now! 
Btw we first installed the 1.0.0 but now we're on dev master.
Sorry for that rookie mistake.

**Comment by kaystrobach** [comment]
No problem - cool that it works now!

**Comment by tritum** [comment]
Awesome. Thanks for your help @kaystrobach!
