### ISSUE TITLE
Fileupload inside repeatable form element email finisher not working

### ISSUE THREAD

**Issue by AlexanderNies** [tritum/repeatable_form_elements#31]
Dear Maintainers of this project,

I tried creating a Multi File Upload with a repeatable_form_elements container and a File Upload Element inside of it. I am currently on Version 11.5.17.
When adding an upload field inside a repeatable form element and trying to send this Data as an E-Mail, I get the following error:

Call to a member function getContents() on array
in /var/www/html/public/typo3/sysext/form/Classes/Domain/Finishers/EmailFinisher.php line 189
                if ($file) {
                    if ($file instanceof FileReference) {
                        $file = $file->getOriginalResource();
                    }
                    $mail->attach($file->getContents(), $file->getName(), $file->getMimeType());
                }
            }
        }

When I try to access the $file inside the EmailFinisher the data is unusable. See screenshot (it should be 2 files).

![Repeatable_Form_Upload_File](https://user-images.githubusercontent.com/118887701/205936830-f3750cd9-fb86-4247-bd12-5efba827fd2e.png)

Thanks a lot for your response.

**Comment by dkassor** [comment]
I can confirm this issue. Is there a solution for that issue?

**Comment by keessonnema** [comment]
Anyone found a possible solution for this? I haven't tried myself yet, but will try to debug it a bit further.

**Comment by markustobler** [comment]
I can confirm that issue.
