### ISSUE TITLE
Typo3 12 compatibility?

### ISSUE THREAD

**Issue by KaiBroenstrup** [tritum/repeatable_form_elements#37]
Anyone got this working in Typo3 v12? Tried to migrate it but there is a problem with the image upload field. Something changed there again in Typo3 v12?

**Comment by helmut-winkelbach** [comment]
I also would need it for TYPO3 v 12.
 "repeatable_form_elements" has 16,448 downloads, should it should have a benefit.

**Comment by helsner** [comment]
we forked the extension, but should be usable either way
https://github.com/toujou/repeatable_form_elements/pull/1/files
I'm not finished with testing, but at least can say that the BE still works with it

**Comment by localhorst** [comment]
> we forked the extension, but should be usable either way https://github.com/toujou/repeatable_form_elements/pull/1/files I'm not finished with testing, but at least can say that the BE still works with it
> 
> the only actual changes are dependencies and objectmanager removal

That's good news. Would you mind to create a pull request?

**Comment by klodeckl** [comment]
So there won‘t be a compatible version because the name changed?

**Comment by alpin3rocker** [comment]
Typo3 12 compatibility would be great. How can this be accelerated? Thanks for an answer...

**Comment by olforestman** [comment]
Atm, we are working on a series of new releases.

**Comment by chrosey** [comment]
As @olforestman said, we are currently working on TYPO3 v12 compatibility. The branch `version/4.x.x` should already be stable under TYPO3 v11 and v12

**Comment by klodeckl** [comment]
Sounds good, thank you!

**Comment by alpin3rocker** [comment]
version/4.x.x works! Install with Composer:
composer.json
{
...
	"require": {
		"tritum/repeatable-form-elements": "dev-version/4.x.x",
	},
	"repositories": [
		{
            "type": "vcs",
            "url": "https://github.com/tritum/repeatable_form_elements",
			"options": {
				"canonical": false
			}
        }
]

Thank's a lot!

**Comment by chrosey** [comment]
Will be solved in #42
