### ISSUE TITLE
Date is not working in a nested container

### ISSUE THREAD

**Issue by jlandsmann** [tritum/repeatable_form_elements#4]
I would like to use your FormElement with an date field inside. Inside the first copy (the original element) everything is fine, but when I have two copies the second date-input gets the following errror:
```
The date '2001-03-12' was not recognized (for format 'Y-m-d\TH:i:sP')
```
Can you help me?

**Comment by stwagner** [comment]
I can confirm the issue. Is there a workaround or at least a hint how to fix it in the code?

**Comment by tritumRz** [comment]
Feel free to test https://github.com/tritum/repeatable_form_elements/pull/9 . It should solve the Probem.

**Comment by tritum** [comment]
PR #9 has been merged. Closing this issue.
