### ISSUE TITLE
fileupload problem 

### ISSUE THREAD

**Issue by miloosh** [tritum/repeatable_form_elements#5]
file upload for repeatable elements is not working in  9.5 LTS

I fixed it in FormHooks.php on line 117 by adding:
>for ($i=1; $i<=10; $i++) {
      $formRuntime->getFormDefinition()->getProcessingRule('repeatablecontainer-1.0.fileupload-'.$i)->setDataType('TYPO3\CMS\Extbase\Domain\Model\FileReference');
}

**Comment by tritumRz** [comment]
Feel free to test https://github.com/tritum/repeatable_form_elements/pull/9 . It should solve the Probem.

**Comment by tritum** [comment]
PR #9 has been merged. Closing this issue.
