### ISSUE TITLE
Compatibility with TYPO3 v10

### ISSUE THREAD

**Issue by arunspawoz** [tritum/repeatable_form_elements#7]
Hello,

Do you've any plan to fix the compatibility of the extension for TYPO3 10.4 LTS? It would be great if you can let me know a plan for this.

Thank you.

**Comment by tritumRz** [comment]
Feel free to test https://github.com/tritum/repeatable_form_elements/pull/9 .

**Comment by arunspawoz** [comment]
Hi @tritumRz Thank you. I will check.

**Comment by tritum** [comment]
PR #9 has been merged. Closing this issue.
