### ISSUE TITLE
Class 'TRITUM\RepeatableFormElements\Hooks\FormHooks' not found

### ISSUE THREAD

**Issue by typo3ua** [tritum/repeatable_form_elements#8]
I installed your `ext: repeatable_form_elements` (copy to the dir `ext`) then added the `repeatable form elements` in my form and saved.

![repeatable_form_elements_error](https://user-images.githubusercontent.com/638022/81500585-c3e0bc80-92db-11ea-88af-8943697b79f8.png)

Added the new form on the frontend and get an error
```
Oops, an error occurred!
Class 'TRITUM\RepeatableFormElements\Hooks\FormHooks' not found
```

#### My instance:
- PHP 7.2
- TYPO3 9.5.16 (install via composer)

**Comment by typo3ua** [comment]
I tried the same with install TYPO3 9.5.16 (classic install with symlink) it works well.

The problem appears only when I install TYPO3 via the composer.

**Comment by tritum** [comment]
@typo3ua do you still experience this behaviour in the current release 3.1.0? Unfortunately, it is v11 only.

**Comment by chrosey** [comment]
Since there was no response to the last question, I will close the issue.

**Comment by typo3ua** [comment]
Sorry! I do not use TYPO3 > 9 ...
